### PR TITLE
implemented mp_fast_close socket option and some bug fixes

### LINKED ISSUE #34: Create Socket option to use the MP_FAST_CLOSE option when closing a socket
Currently the MP_FAST_CLOSE option is only used to reset the mp_dccp connection whenever there is a malformed option in a packet. However, MP_FAST_CLOSE  could also be used to reset mp-dccp connection when an application requires it. To enable this, an additional socket option has to be created, whenever this socket option is set and the close function of the meta socket is called, the MP_FAST_CLOSE option will be used.

### PR DESCRIPTION
**Pull request by LeonardWalter**
This PR implements:

an MP_FAST_CLOSE reset code for MPDCCP sockets (Issue #33)
`DCCP_RESET_CODE_MPDCCP_ABORTED = 13`

a socket option to use MP_FAST_CLOSE - `DCCP_SOCKOPT_MP_FAST_CLOSE = 23` (Issue #34)

can be called like this:
```
int val = 1;
setsockopt(sock, SOL_DCCP, 23, (char*)&val, sizeof(val));
```
can also be set back to normal closing procedure with val=0

with other socketoptions, you can change the scheduler and reordering algorithm.
scheduler module needs to be loaded first though e.g. with `insmod mpdccp_sched_rr` 
`setsockopt(sock, SOL_DCCP, 21, "rr", sizeof("rr"));` 

`dccp_setsockopt` is overwritten on meta socket creation with `mpdccp_setsockopt` and vice versa on close_meta.

I added two new variables to the mpcb struct.
`int close_fast;` is what is influenced by setsockoption DCCP_SOCKOPT_MP_FAST_CLOSE
`int close_opt_rcv` is set if we receive either MP_CLOSE or MP_FAST_CLOSE

I changed the closing procedure a little on the server side for scenarios where the client closes the connection.
Now the mpcb will be destroyed and only the listening socket stays open.

Unrelated to the rest of the PR, I added a new check for the sk_state to the retransmit worker.

### CODE REVIEW

**Comment by LeonardWalter** [comment]
updated the PR, and added a small check to avoid calling `mpdccp_close_meta()` multiple times.

**Comment by NathalieRM** [comment]
Hi @LeonardWalter 

I wanted to test this PR, but the compilation fails.

  CC [M]  drivers/hid/hid-sunplus.o
  CC [M]  drivers/gpu/drm/i915/i915_gem_gtt.o
net/dccp/options.c: In function ‘dccp_parse_options’:
net/dccp/options.c:375:37: error: ‘mpcb’ undeclared (first use in this function)
     if(is_mpdccp(sk) && len > 7 && !mpcb->close_opt_rcv){
                                     ^~~~
  AR      drivers/scsi/built-in.o
  AR      drivers/built-in.o
scripts/package/Makefile:91: die Regel für Ziel „bindeb-pkg“ scheiterte
make[1]: *** [bindeb-pkg] Fehler 2
Makefile:1374: die Regel für Ziel „bindeb-pkg“ scheiterte
make: *** [bindeb-pkg] Fehler 2
root@ztc02:/..._dev/mp-dccp > 

Could you please double check if all the necessary changes are included?

Br, 

Nathalie

**Comment by LeonardWalter** [comment]
sorry that was my bad, pushed the corrected commit now

**Comment by NathalieRM** [comment]
Hi @LeonardWalter 

Thanks, I can compile it now. I run some tests and I can see that the socket option works fine, and a reset packet is sent to close the connection (instead of the regular Close or CloseReq packets), however I still see some problems.

1. The draft specifies that the MP_FAST_CLOSE option must be sent in a reset packet with reset code 13. As I said, I can see the reset packet, but this doesn't have any MP_OPTION, and the reset code I see is 2.

2. As a response to the first reset packet with the MP_FAST_CLOSE option, the host must reply as well with a reset. In my test I see the response is a CloseReq packet


Screenshot from 2023-04-11 15-51-25

Ps. I am not sure if I am missing something in my tests, I just use iperf and set the MP_FAST_CLOSE socket option after the mp-dccp socket option is set. I assume the socket option works because at least the reset packet is sent, but I am not sure if I have to set something else. Can you please clarify how did you perform your tests?

**Comment by LeonardWalter** [comment]
this pr is obsolete, it was succeeded by pr #53

**Pull request closed without merging**
